repos:
  - repo: https://github.com/psf/black
    rev: v25.1.0  # Neueste Version prüfen
    hooks:
      - id: black
        name: black (Python code formatter)
        language: python
        types: [ python ]

  - repo: https://github.com/pycqa/isort
    rev: v5.13.2  # Überprüfe die neueste Version
    hooks:
      - id: isort
        name: isort (Python import sorter)
        language: python
        types: [python]
        args: ['--profile', 'black']

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Neueste Version prüfen
    hooks:
      - id: flake8
        name: flake8 (Python linting)
        language: python
        types: [ python ]